### ISSUE TITLE
!kb lässt GLaDOS crashen

### ISSUE THREAD

**Issue by seegras3** [maddin77/GLaDOS#36]
<seegras> !kb ChuckNorriso kthxbye
* Aegir has quit (A TLS packet with unexpected length was received.)
* KeratBot has kicked ChuckNorriso from #sa-mp.de (kthxbye (seegras))
* KeratBot sets modes [#sa-mp.de +b *!*@KN-thddql.torservers.net]
* Aegir (Aegir@KN-hqnl7l.92-222-115.eu) has joined
* KeratBot sets modes [#sa-mp.de +h Aegir]

Logmitschnitt hab ich noch keinen, reich ich demnächst nach

**Comment by maddin77** [comment]
Kann ich nicht reproduzieren, und ist vermutlich gefixxt da ich das neu geschrieben habe. Falls nicht einfach wieder öffnen.
